services:
  cb-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: certusbuild/planning-app:latest
    container_name: cb-app
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      # Override certain values from env file if needed
      - REDIS_URL=redis://redis:6379
      # Enable authentication bypass for testing
      - AUTH_BYPASS_ENABLED=${AUTH_BYPASS_ENABLED}
      - PORT=18000
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - AUTH_CALLBACK_URL=${AUTH_CALLBACK_URL}
      - AUTH_SCOPE=openid profile email
    ports:
      - 18000:18000
    volumes:
      - certusbuild_data1:/app/public/content
      - certusbuild_uploads1:/app/public/uploads
    depends_on:
      - redis
    networks:
      npm:
        aliases:
          - certusbuild-planning
          - cb-planning

  # Redis for session storage
  redis:
    image: redis:alpine
    container_name: cb-redis
    restart: unless-stopped
    volumes:
      - redis_data1:/data
    networks:
      npm:
        aliases:
          - redis
          - memdb
    command: redis-server --appendonly yes

  # Nginx reverse proxy
  nginx:
    image: nginx:stable-alpine
    container_name: cb-nginx
    restart: unless-stopped
    ports:
      - "18080:80"
      - "18443:443"
    volumes:
      - ./nginx/certusbuild.conf:/etc/nginx/conf.d/certusbuild.conf
      - ./nginx/logs:/var/log/nginx
      - ./certs:/certs:ro
#      - ./certbot/www:/var/www/certbot
    networks:
      npm:
        aliases:
          - nginx
          - webserve
    depends_on:
      - cb-app

  # Certbot for SSL certificates
#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  npm:
    external: true

volumes:
  certusbuild_data1:
    external: true
  certusbuild_uploads1:
    external: true
  redis_data1:
    external: true
