tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Planning CertusBuild App service
  - hostname: planning.certusbuild.com
    service: http://certusbuild-planning:5000
    originRequest:
      connectTimeout: 10s
      noTLSVerify: false
      
  # Catch-all (return 404)
  - service: http_status:404